#!/usr/bin/env bash
# 00a_setup_env.sh — WSL Ubuntu 24.04 variant of 00_setup_env.sh.
#
# Differences from 00_setup_env.sh (server):
# - Creates minimax_h3 env from scratch (python=3.11 + pip torch cu124),
#   NOT a `conda create -n minimax_h3 --clone doll` (the `doll` env doesn't
#   exist on WSL; also `--clone` may hit TUNA mirror 403 / proxy SSL on server).
# - Installs CUDA toolkit (nvcc) via conda (env-local, no sudo/apt) — only
#   needed by 07 FlashVSR's Block-Sparse-Attention CUDA kernel; skip with
#   SKIP_CUDA_TOOLKIT=1 if you don't plan to run 07.
# - Installs gxx_linux-64=12 (C++20 <concepts> for SGLang JIT kernel fusion).
# - Clones FlashVSR + Block-Sparse-Attention to ~/repos/ (Linux filesystem,
#   fast compile — compiling BSA CUDA kernel on /mnt/c is slow/error-prone).
# - Sets SGLANG_SRC / DIFFUSERS_SRC to ~/repos/ (persistent across reboots,
#   vs the server default /tmp/sglang-src which gets wiped on reboot).
# - Writes WSL path overrides to proxy.env so scripts 01-08 pick them up
#   automatically (no need to set env vars every time).
# - Runs `conda init bash` so interactive shells have conda on PATH.
# - No corporate proxy / CA bundle workarounds (direct internet at home).
# - Reuses 00_setup_env.sh for the SGLang install (pip sglang[all] + git
#   editable + qwen3_asr / flash_attention_v3 patches) — no logic duplication.
#
# Usage:
#   bash minimax_h3/00a_setup_env.sh                # full setup (no FlashVSR deps)
#   SKIP_CUDA_TOOLKIT=1 bash minimax_h3/00a_setup_env.sh   # skip nvcc (only for 07)
#   SKIP_FLASHVSR=1 bash minimax_h3/00a_setup_env.sh       # skip cloning FlashVSR/BSA
#
# Override CUDA version (default 12.4 to match wsl/README.md):
#   CUDA_TOOLKIT_LABEL=nvidia/label/cuda-12.1.1 \
#   TORCH_INDEX_URL=https://download.pytorch.org/whl/cu121 \
#   bash minimax_h3/00a_setup_env.sh
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# ── 1. Source conda (must exist; miniconda3 at ~/miniconda3) ──────────────
# wsl/README.md step 7 installs miniconda to ~/miniconda3 and `conda init bash`.
CONDA_BASE="$HOME/miniconda3"
if [ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]; then
    echo "❌ ERROR: miniconda3 not found at $CONDA_BASE" >&2
    echo "       Install first (see wsl/README.md step 7):" >&2
    echo "         curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh" >&2
    echo "         bash /tmp/miniconda.sh -b -p $CONDA_BASE" >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# Accept ToS for default channels (conda 26.x requires it; older versions ignore).
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main 2>/dev/null || true
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r 2>/dev/null || true

# ── 2. WSL path defaults (Linux fs: repos ~/repos, weights ~/model) ───────
# Exported BEFORE sourcing _env.sh so its ${VAR:-default} picks these up.
# Also written to proxy.env (step 3) so scripts 01-08 inherit them.
export MODEL_DIR="${MODEL_DIR:-$HOME/model/MiniMax-H3}"
export WEIGHTS_ROOT="${WEIGHTS_ROOT:-$HOME/model}"
export RESULTS_DIR="${RESULTS_DIR:-$HOME/output/minimaxh3_rotate_results}"
export FLASHVSR_DIR="${FLASHVSR_DIR:-$HOME/repos/FlashVSR}"
export BSA_DIR="${BSA_DIR:-$HOME/repos/Block-Sparse-Attention}"
export FLASHVSR_MODEL_DIR="${FLASHVSR_MODEL_DIR:-$HOME/model/FlashVSR}"
# Persistent source clones (server default /tmp/* gets wiped on reboot;
# SGLang editable install + diffusers git main would have to re-clone each boot).
export SGLANG_SRC="${SGLANG_SRC:-$HOME/repos/sglang-src}"
export DIFFUSERS_SRC="${DIFFUSERS_SRC:-$HOME/repos/diffusers-src}"

# ── 3. Write proxy.env with WSL path overrides (if not exists) ────────────
# proxy.env is at repo root ($REPO_DIR/proxy.env), gitignored.
# _env.sh sources it before setting ${VAR:-default} defaults, so all scripts
# 01-08 will automatically use the WSL Linux-filesystem paths.
PROXY_ENV="$REPO_DIR/proxy.env"
if [ ! -f "$PROXY_ENV" ]; then
    echo "📦 writing WSL path overrides -> $PROXY_ENV"
    cat > "$PROXY_ENV" <<'ENVEOF'
# proxy.env — WSL Ubuntu 24.04 path overrides (auto-generated by 00a_setup_env.sh).
# No corporate proxy needed (direct internet). Just path overrides + HF_TOKEN.
#
# ⚠️ Fill HF_TOKEN before running step 01 (MiniMax-H3 weights may be gated):
#    1. Open https://huggingface.co/MiniMaxAI/MiniMax-H3 and accept license.
#    2. Create token:  https://huggingface.co/settings/tokens
#    3. Uncomment + fill below:
# export HF_TOKEN="hf_xxx"

# HF mirror (huggingface.co 直连可能超时; 用 hf-mirror.com 镜像加速)
export HF_ENDPOINT="https://hf-mirror.com"

# Repos + weights on Linux filesystem (fast I/O for model load + compilation).
export MODEL_DIR="$HOME/model/MiniMax-H3"
export WEIGHTS_ROOT="$HOME/model"
export RESULTS_DIR="$HOME/output/minimaxh3_rotate_results"
export FLASHVSR_DIR="$HOME/repos/FlashVSR"
export BSA_DIR="$HOME/repos/Block-Sparse-Attention"
export FLASHVSR_MODEL_DIR="$HOME/model/FlashVSR"

# Persistent source clones (server default /tmp/* wiped on reboot).
export SGLANG_SRC="$HOME/repos/sglang-src"
export DIFFUSERS_SRC="$HOME/repos/diffusers-src"
ENVEOF
    echo "  ✅ written (edit to add HF_TOKEN before step 01)"
else
    echo "⏭️  proxy.env already exists: $PROXY_ENV (not overwriting)"
    echo "  ⚠️ If it has server paths, back up + rerun to regenerate:"
    echo "     mv $PROXY_ENV ${PROXY_ENV}.server.bak && bash $0"
fi

# ── 4. Source _env.sh (picks up our exports + proxy.env) ──────────────────
# _env.sh: proxy.env sourcing, conda fallback + activate, GPU, CA bundle.
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_env.sh"

echo "=== [00a] Setup minimax_h3 env on WSL ==="
echo "  🤖 model:      $MODEL_DIR"
echo "  🏋️ weights:    $WEIGHTS_ROOT"
echo "  💾 output:      $RESULTS_DIR"
echo "  📦 FlashVSR:   $FLASHVSR_DIR"
echo "  📦 BSA:         $BSA_DIR"
echo "  📦 SGLang src: $SGLANG_SRC"
echo "  🏠 conda env:  $CONDA_ENV  (at $CONDA_PREFIX)"
echo ""

# ── 5. Create minimax_h3 env from scratch (no doll clone) ─────────────────
_new_prefix="$(conda info --base 2>/dev/null)/envs/$CONDA_ENV"
if [ -d "$_new_prefix/conda-meta" ] && [ -f "$_new_prefix/conda-meta/history" ]; then
    echo "--- conda env '$CONDA_ENV' already exists at $_new_prefix ---"
else
    echo "📦 creating conda env '$CONDA_ENV' (python=3.11) from scratch..."
    conda create -y -n "$CONDA_ENV" python=3.11 || {
        echo "❌ conda create failed" >&2
        exit 1
    }
    echo "  ✅ created"
fi

# Activate (force-source conda.sh again — `conda create` may reset shell hooks).
# shellcheck disable=SC1091
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"
echo "  🐍 python: $(python --version 2>&1) at $(which python)"

# Verify CPython (not GraalPy — gxx_linux-64 can cause a swap).
_impl="$(python -c "import platform; print(platform.python_implementation())" 2>/dev/null)"
if [ "$_impl" != "CPython" ]; then
    echo "❌ ERROR: python is $_impl, not CPython. Recreate env:" >&2
    echo "       conda env remove -n $CONDA_ENV && bash $0" >&2
    exit 1
fi

# ── 6. Install PyTorch (pip, cu124) ───────────────────────────────────────
# Matches wsl/README.md step 6/7 (CUDA 12.4 toolkit + cu124 torch wheel).
# SGLang git main pins torch==2.13.0 (CUDA 13) but 00_setup_env.sh installs
# sglang with --no-deps, so env's cu124 torch is reused. flashinfer has prebuilt
# wheels for cu124 + torch 2.x, so this combo works.
TORCH_INDEX_URL="${TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu124}"
if ! python -c "import torch; assert torch.cuda.is_available()" 2>/dev/null; then
    echo "📦 installing PyTorch (cu124)..."
    pip install --index-url "$TORCH_INDEX_URL" torch torchvision || {
        echo "❌ torch install failed" >&2
        echo "  Try cu121: TORCH_INDEX_URL=https://download.pytorch.org/whl/cu121 bash $0" >&2
        exit 1
    }
fi
python -c "import torch; print(f'  ✅ torch {torch.__version__}  cuda={torch.version.cuda}  available={torch.cuda.is_available()}')"

# ── 7. Install CUDA toolkit (nvcc) + gcc via conda ────────────────────────
# nvcc is only needed to compile Block-Sparse-Attention's CUDA kernel (07).
# SGLang serves prebuilt flashinfer kernels; diffusers MiniMax + torchao int8
# use prebuilt binaries — they don't need nvcc. So SKIP_CUDA_TOOLKIT=1 is safe
# if you don't plan to run 07.
CUDA_TOOLKIT_LABEL="${CUDA_TOOLKIT_LABEL:-nvidia/label/cuda-12.4.0}"

if [ "${SKIP_CUDA_TOOLKIT:-0}" != "1" ]; then
    if ! command -v nvcc >/dev/null 2>&1; then
        echo "📦 installing CUDA toolkit ($CUDA_TOOLKIT_LABEL)..."
        conda install -y -c "$CUDA_TOOLKIT_LABEL" cuda-toolkit || {
            echo "❌ cuda-toolkit install failed" >&2
            echo "  Skip with: SKIP_CUDA_TOOLKIT=1 bash $0 (only needed for 07 FlashVSR BSA kernel)" >&2
            echo "  Or try 12.1: CUDA_TOOLKIT_LABEL=nvidia/label/cuda-12.1.1 bash $0" >&2
            exit 1
        }
    fi
    echo "  ✅ nvcc: $(nvcc --version 2>/dev/null | tail -1 | xargs)"
else
    echo "⏭️  SKIP_CUDA_TOOLKIT=1 — skipping nvcc (07 FlashVSR BSA kernel compile will fail)"
fi

# gcc 12 for SGLang C++20 JIT kernel fusion (QKNorm+RoPE). Always install —
# without it, JIT fallback to slower Python impl, or worse, worker hang.
# pin python=3.11 to prevent gxx_linux-64 swapping CPython → GraalPy.
if ! command -v x86_64-conda-linux-gnu-gcc >/dev/null 2>&1; then
    echo "📦 installing gcc 12 (gxx_linux-64=12, python=3.11 pinned)..."
    conda install -y -c conda-forge gxx_linux-64=12 python=3.11 || {
        echo "  ⚠️ gxx install failed; trying system gcc" >&2
    }
fi
_gcc="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc"
_gpp="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++"
if [ -x "$_gcc" ] && [ -x "$_gpp" ]; then
    echo "  ✅ gcc: $($_gcc --version | head -1)"
    # Ensure bare `gcc`/`g++`/`cc`/`c++` resolve to conda's g++-12 (00_setup_env.sh's
    # C++20 check uses bare `g++`; conda gxx_linux-64 may only create the prefixed name).
    for _bare in gcc g++ cc c++; do
        _target="$_gpp"
        case "$_bare" in gcc|cc) _target="$_gcc" ;; esac
        if [ ! -e "$CONDA_PREFIX/bin/$_bare" ] && [ -x "$_target" ]; then
            ln -sf "$(basename "$_target")" "$CONDA_PREFIX/bin/$_bare"
        fi
    done
    unset _bare _target
    # Export so 02_serve.sh's CXX detection picks it up, and BSA setup.py finds it.
    export CUDA_HOME="${CUDA_HOME:-$CONDA_PREFIX}"
    export PATH="$CUDA_HOME/bin:$PATH"
    export CC="$_gcc" CXX="$_gpp"
else
    echo "  ⚠️ conda gcc not found; trying system gcc/g++" >&2
    command -v gcc >/dev/null 2>&1 && echo "  gcc: $(gcc --version | head -1)" || echo "  ❌ no gcc" >&2
fi

# ── 8. Pre-clone FlashVSR + BSA to ~/repos/ (for 07, Linux fs) ────────────
# 07_flashvsr_sr.sh clones these on first INSTALL_DEPS=1 run; pre-cloning to
# ~/repos/ (Linux fs) ensures the CUDA kernel compiles fast (compiling on /mnt/c
# is 5-10× slower). 07 will skip clone if dir already present.
# Skip with SKIP_FLASHVSR=1 if you only want 02/03/06/06a/06b (no SR).
if [ "${SKIP_FLASHVSR:-0}" != "1" ]; then
    mkdir -p "$(dirname "$FLASHVSR_DIR")" "$(dirname "$BSA_DIR")"
    if [ ! -d "$FLASHVSR_DIR/diffsynth" ]; then
        echo "📦 cloning FlashVSR -> $FLASHVSR_DIR"
        git clone --depth 1 https://github.com/OpenImagingLab/FlashVSR.git "$FLASHVSR_DIR" || \
            git -c http.sslVerify=false clone --depth 1 https://github.com/OpenImagingLab/FlashVSR.git "$FLASHVSR_DIR"
    else
        echo "⏭️  FlashVSR already present: $FLASHVSR_DIR"
    fi
    if [ ! -d "$BSA_DIR/block_sparse_attn" ]; then
        echo "📦 cloning Block-Sparse-Attention -> $BSA_DIR"
        git clone --depth 1 https://github.com/mit-han-lab/Block-Sparse-Attention.git "$BSA_DIR" || \
            git -c http.sslVerify=false clone --depth 1 https://github.com/mit-han-lab/Block-Sparse-Attention.git "$BSA_DIR"
    else
        echo "⏭️  Block-Sparse-Attention already present: $BSA_DIR"
    fi
else
    echo "⏭️  SKIP_FLASHVSR=1 — skipping FlashVSR/BSA clone (07 disabled)"
fi

# ── 9. Install SGLang (reuse 00_setup_env.sh) ─────────────────────────────
# 00_setup_env.sh already has the full SGLang install logic:
#   - pip install -U "sglang[all]" + "sglang[diffusion]"
#   - self-check --model-variant (Diffusion serving arg)
#   - if missing: git clone sglang + editable install --no-deps (compat mode)
#     + qwen3_asr patch (exist_ok=True) + flash_attention_v3 patch (inspect.signature)
#   - align diffusers/peft/transformers==5.12.1/huggingface_hub/xgrammar
# We set SGLANG_SRC=~/repos/sglang-src (persistent) so the editable install
# survives reboots. 00 sources _env.sh (now WSL-aware) and picks up our env.
echo "📦 installing SGLang via 00_setup_env.sh (INSTALL_DEPS=1)..."
INSTALL_DEPS=1 bash "$SCRIPT_DIR/00_setup_env.sh" || {
    echo "❌ SGLang install failed (see errors above)" >&2
    echo "  Manual retry: INSTALL_DEPS=1 bash minimax_h3/00_setup_env.sh" >&2
    exit 1
}

# ── 10. Install huggingface_hub (for 01_download_models.sh) ───────────────
# 01 uses `hf download` CLI + a fallback Python downloader. Both need
# huggingface_hub. sglang[all] pulls it but pin to latest for HF_ENDPOINT mirror.
if ! python -c "import huggingface_hub" 2>/dev/null; then
    echo "📦 installing huggingface_hub..."
    pip install --upgrade huggingface_hub || echo "  ⚠️ huggingface_hub install failed" >&2
fi

# ── 10b. Install av (PyAV, for diffusers encode_video 写 mp4) ─────────────
# 06c/06d/06a/06b 的 generate 调 diffusers.utils.export_utils.encode_video 写
# mp4+音频，依赖 PyAV（av 包，manylinux wheel 内嵌 ffmpeg 库，无需系统 ffmpeg）。
# 没装会报 "PyAV is required to use `encode_video`. You can install it with `pip install av`."
if ! python -c "import av" 2>/dev/null; then
    echo "📦 installing av (PyAV, for encode_video mp4 output)..."
    pip install av || echo "  ⚠️ av install failed (encode_video 会报错，手动: pip install av)" >&2
fi

# ── 11. conda init bash (so interactive shells have conda on PATH) ─────────
if ! grep -q "miniconda3" "$HOME/.bashrc" 2>/dev/null; then
    echo "📦 running 'conda init bash'..."
    conda init bash
    echo "  ✅ conda initialized in ~/.bashrc"
    echo "  ⚠️ Run 'source ~/.bashrc' or restart your shell before running scripts 01-08"
else
    echo "⏭️  conda already initialized in ~/.bashrc"
fi

# ── 12. Verify ─────────────────────────────────────────────────────────────
echo ""
echo "--- verification ---"
[ -d "$FLASHVSR_DIR/diffsynth" ] && echo "  ✅ FlashVSR code" || echo "  [---] FlashVSR code (SKIP_FLASHVSR=1; step 07 disabled)"
[ -d "$BSA_DIR/block_sparse_attn" ] && echo "  ✅ BSA code" || echo "  [---] BSA code (SKIP_FLASHVSR=1; step 07 disabled)"
python -c "import torch; print(f'  ✅ torch {torch.__version__} cuda={torch.cuda.is_available()}')" 2>/dev/null || echo "  [MISS] torch"
python -c "import sglang; print(f'  ✅ sglang {getattr(sglang, \"__version__\", \"unknown\")}')" 2>/dev/null || echo "  [MISS] sglang"
python -c "from diffusers.modular_pipelines.minimax_h3 import MiniMaxH3ModularPipeline; print('  ✅ diffusers MiniMax-H3 module')" 2>/dev/null || \
    echo "  [---] diffusers MiniMax-H3 module (06/06a/06b will auto-install on first run)"
python -c "import av; print(f'  ✅ av {av.__version__} (encode_video mp4 输出)')" 2>/dev/null || \
    echo "  [MISS] av (06c/06d encode_video 会报错，pip install av)"
if [ "${SKIP_CUDA_TOOLKIT:-0}" != "1" ]; then
    command -v nvcc >/dev/null 2>&1 && echo "  ✅ nvcc (for 07 BSA kernel)" || echo "  [MISS] nvcc (07 BSA kernel compile will fail)"
fi
command -v x86_64-conda-linux-gnu-gcc >/dev/null 2>&1 && echo "  ✅ gcc 12 (C++20 JIT)" || echo "  [---] gcc 12 (JIT fallback to slower Python impl)"

# Weights (user must download separately — gated + ~120GB)
if [ -f "$MODEL_DIR/model_index.json" ]; then
    echo "  ✅ MiniMax-H3 weights (model_index.json present)"
else
    echo "  [---] MiniMax-H3 weights (run: HF_TOKEN=hf_xxx bash minimax_h3/01_download_models.sh)"
fi

echo ""
echo "🎉 [00a] Done. Next:"
echo "  1. source ~/.bashrc  (activate conda for your shell)"
echo "  2. Edit $PROXY_ENV — fill HF_TOKEN (MiniMax-H3 may be gated)"
echo "  3. Download weights (FL2VA ~120GB):"
echo "       HF_TOKEN=hf_xxx bash minimax_h3/01_download_models.sh"
echo "  4. Generate (single-GPU WSL — use 06b Turbo LoRA + auto offload):"
echo "       GPU=0 MODEL_PATH=$MODEL_DIR \\"
echo "         LORA_PATH=$HOME/model/MiniMax-H3-Turbo/minimax_h3_fl2v_turbo_4step_v1.0_768p_bf16.safetensors \\"
echo "         DEVICE=cuda:0 FIRST_FRAME=~/my_images/subject.jpg PROMPT=\"...\" \\"
echo "         OUTPUT_DIR=$RESULTS_DIR/results_turbo OUTPUT_NAME=rotate.mp4 \\"
echo "         bash minimax_h3/06b_turbo_lora_inference.sh"
echo ""
echo "  ⚠️  See README_wsl.md for VRAM constraints (RTX 3090 24GB → only 06b viable)."
