#!/usr/bin/env bash
# 03_train.sh — Stage 2: train the full EVA-Gaussian (depthnet + Gaussian
# splatting renderer + feature refiner) using the stage-1 pretrained depthnet.
#
# Runs train.py from the EVA-Gaussian repo with:
#   --cfg_path  config/train.yaml  (generated by make_config.py)
#   --log_path  $RESULTS_DIR/experiments
#
# Output: $RESULTS_DIR/experiments/train_EVAGaussian_MMDD/{ckpt,show,logs,file}/
#
# Env:
#   DATA_ROOT=/path/to/dataset      (required)
#   STAGE1_CKPT=/path/to/stage1.pth  (required if not auto-detected)
#   GPU=0                           (physical GPU id)
#   ANCHOR=1                        (enable anchor loss)
#   LR=0.0005  BATCH_SIZE=2  NUM_STEPS=100000  (hyperparameter overrides)
#   SOURCE_ID=0,1  TRAIN_NOVEL_ID=2,3,4  VAL_NOVEL_ID=3
#   USE_HR_IMG=1                    (use high-res images)
#   RESUME_CKPT=/path/to/train_latest.pth  (resume full training from ckpt)
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_env.sh"

DATA_ROOT="${DATA_ROOT:?❌ DATA_ROOT env var required}"

# Ensure EVA-Gaussian repo is cloned.
if [ ! -f "$EVA_DIR/train.py" ]; then
    echo "❌ ERROR: $EVA_DIR/train.py not found." >&2
    echo "       Run INSTALL_DEPS=1 BUILD_CUDA=1 bash $SCRIPT_DIR/00_setup_env.sh first" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Find stage-1 checkpoint (auto-detect or use STAGE1_CKPT / RESUME_CKPT).
# ---------------------------------------------------------------------------
EXP_DIR="$RESULTS_DIR/experiments"

if [ -n "${RESUME_CKPT:-}" ]; then
    # Resume mode: skip stage1_ckpt logic.
    echo "🏋️ [03] resume mode — checkpoint: $RESUME_CKPT"
    STAGE1_CKPT="${STAGE1_CKPT:-}"
elif [ -z "${STAGE1_CKPT:-}" ]; then
    # Auto-detect the latest stage-1 checkpoint (prefer _final, fall back to _latest).
    echo "🔍 [03] auto-detecting stage-1 checkpoint"
    STAGE1_CKPT="$(find "$EXP_DIR" -name 'pretrain_*_final.pth' 2>/dev/null | sort | tail -1)"
    if [ -z "$STAGE1_CKPT" ]; then
        STAGE1_CKPT="$(find "$EXP_DIR" -name 'pretrain_*_latest.pth' 2>/dev/null | sort | tail -1)"
    fi
    if [ -z "$STAGE1_CKPT" ]; then
        echo "❌ ERROR: no stage-1 checkpoint found in $EXP_DIR" >&2
        echo "       Run 02_pretrain_depth.sh first, or set STAGE1_CKPT=/path/to/stage1.pth" >&2
        exit 1
    fi
fi

if [ -n "${STAGE1_CKPT:-}" ]; then
    if [ -f "$STAGE1_CKPT" ]; then
        echo "🏋️ [03] stage1_ckpt: $STAGE1_CKPT"
    else
        echo "❌ ERROR: STAGE1_CKPT not found: $STAGE1_CKPT" >&2
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# 2. Generate train.yaml (with stage1_ckpt).
# ---------------------------------------------------------------------------
export DATA_ROOT EVA_DIR STAGE1_CKPT
python "$SCRIPT_DIR/make_config.py" train

# If resuming, patch restore_ckpt into the config.
if [ -n "${RESUME_CKPT:-}" ]; then
    echo "🏋️ [03] resume from checkpoint: $RESUME_CKPT"
    python - "$EVA_DIR/config/train.yaml" "$RESUME_CKPT" <<'PY'
import sys
path, ckpt = sys.argv[1], sys.argv[2]
with open(path) as f:
    txt = f.read()
lines = [l for l in txt.splitlines() if not l.startswith("restore_ckpt:")]
lines.insert(1, f"restore_ckpt: '{ckpt}'")
with open(path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"  ✅ patched restore_ckpt -> {ckpt}")
PY
fi

# ---------------------------------------------------------------------------
# 3. Run train.py.
# ---------------------------------------------------------------------------
mkdir -p "$EXP_DIR"

echo "🚀 [03] train EVA-Gaussian (stage 2)"
echo "  🤖 model: EVANet (with_gs_render=True) + feature_refiner"
echo "  📁 DATA_ROOT:   $DATA_ROOT"
echo "  🏋️ stage1_ckpt: ${STAGE1_CKPT:-none}"
echo "  💾 output:      $EXP_DIR/train_EVAGaussian_*/"
echo "  🎮 GPU:          ${GPU:-unset}"
echo ""

# train.py accepts --cfg_path and --log_path. Run from $EVA_DIR so relative
# imports (lib.*, config.*) resolve.
cd "$EVA_DIR"
python train.py \
    --cfg_path config/train.yaml \
    --log_path "$EXP_DIR"
if [ $? -ne 0 ]; then
    echo "❌ FAILED: train.py" >&2
    exit 1
fi

LATEST_CKPT="$(find "$EXP_DIR" -path '*/train_EVAGaussian_*' -name '*_final.pth' 2>/dev/null | sort | tail -1)"
if [ -z "$LATEST_CKPT" ]; then
    LATEST_CKPT="$(find "$EXP_DIR" -path '*/train_EVAGaussian_*' -name '*_latest.pth' 2>/dev/null | sort | tail -1)"
fi
echo ""
echo "🎉 [03] Done. EVA-Gaussian training complete."
if [ -n "$LATEST_CKPT" ]; then
    echo "    🏋️ checkpoint: $LATEST_CKPT"
    echo "    🖼️ rendered samples: $(dirname "$LATEST_CKPT")/../show/"
fi
echo "    TensorBoard: tensorboard --logdir $EXP_DIR"
