#!/usr/bin/env bash
# 00a_setup_env.sh — WSL Ubuntu 24.04 variant of 00_setup_env.sh.
#
# Differences from 00_setup_env.sh (server):
# - Creates osediff env from scratch (python=3.10 + pip torch cu118), NOT a clone
#   of the server's env (which doesn't exist on WSL).
# - Installs CUDA toolkit (nvcc) + gcc via conda only when a CUDA ext must be
#   compiled (xformers ships prebuilt wheels for torch 2.0.1 — usually no nvcc
#   needed). Kept here as a fallback when the prebuilt wheel is unavailable.
# - Clones repo to ~/repos/ and weights to ~/model/ (Linux filesystem, fast I/O).
# - Writes WSL path overrides to proxy.env so scripts 01-08 pick them up
#   automatically (no need to set env vars every time).
# - Uses Tsinghua PyPI mirror + HF mirror (hf-mirror.com) — no corporate proxy.
# - Runs `conda init bash` so interactive shells have conda on PATH.
#
# Usage:
#   bash osediff/00a_setup_env.sh              # full setup (env + repo)
#   INSTALL_DEPS=1 bash osediff/00a_setup_env.sh   # also pip install -r requirements
#
# Override torch CUDA build (default cu118, matches requirements.txt torch==2.0.1):
#   TORCH_INDEX_URL=https://download.pytorch.org/whl/cu118 bash osediff/00a_setup_env.sh
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# ── 1. Source conda (must exist; miniconda3 at ~/miniconda3) ──────────────
CONDA_BASE="$HOME/miniconda3"
if [ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]; then
    echo "❌ ERROR: miniconda3 not found at $CONDA_BASE" >&2
    echo "       Install first:" >&2
    echo "         curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh" >&2
    echo "         bash /tmp/miniconda.sh -b -p $CONDA_BASE" >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# Accept ToS for default channels (conda 26.x requires it; older versions ignore).
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main 2>/dev/null || true
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r 2>/dev/null || true

# ── 2. WSL path defaults (Linux fs: repos ~/repos, weights ~/model) ───────
# Exported BEFORE sourcing _env.sh so its ${VAR:-default} picks these up.
# Also written to proxy.env (step 3) so scripts 01-08 inherit them.
export OSEDIFF_DIR="${OSEDIFF_DIR:-$HOME/repos/OSEDiff}"
export MODEL_DIR="${MODEL_DIR:-$HOME/model/osediff}"
export RESULTS_DIR="${RESULTS_DIR:-$HOME/output/osediff_results}"
export EXPERIMENTS_DIR="${EXPERIMENTS_DIR:-$HOME/output/osediff_experiments}"

# ── 3. Write proxy.env with WSL path overrides (if not exists) ────────────
# proxy.env is at repo root ($REPO_DIR/proxy.env), gitignored.
# _env.sh sources it before setting ${VAR:-default} defaults, so all scripts
# 01-08 will automatically use the WSL Linux-filesystem paths.
PROXY_ENV="$REPO_DIR/proxy.env"
if [ ! -f "$PROXY_ENV" ]; then
    echo "📦 creating $PROXY_ENV (WSL overrides; no proxy creds needed at home)"
    cat > "$PROXY_ENV" <<'ENVEOF'
# proxy.env — WSL Ubuntu 24.04 overrides (auto-generated by osediff/00a_setup_env.sh).
# No corporate proxy (direct internet at home). Path overrides + mirrors.
# (Other algos may append their own vars below — this file is shared.)
#
# ⚠️ Fill HF_TOKEN only for gated weights (SD2.1-base is public):
# export HF_TOKEN="hf_xxx"
ENVEOF
    echo "  ✅ created"
fi

# Idempotently append any missing vars (coexists with other algos' vars).
# Runs every time; only adds what's absent.
ensure_line() {
    local k="$1" v="$2"
    if ! grep -q "^export $k=" "$PROXY_ENV" 2>/dev/null; then
        printf 'export %s=%s\n' "$k" "$v" >> "$PROXY_ENV"
        echo "  ➕ added $k"
    fi
}
echo "📦 ensuring OSEDiff vars in $PROXY_ENV"
ensure_line HF_ENDPOINT '"https://hf-mirror.com"'
ensure_line PIP_INDEX_URL '"https://pypi.tuna.tsinghua.edu.cn/simple"'
ensure_line PIP_TRUSTED_HOST '"pypi.tuna.tsinghua.edu.cn"'
ensure_line OSEDIFF_DIR '"$HOME/repos/OSEDiff"'
ensure_line MODEL_DIR '"$HOME/model/osediff"'
ensure_line RESULTS_DIR '"$HOME/output/osediff_results"'
ensure_line EXPERIMENTS_DIR '"$HOME/output/osediff_experiments"'

# ── 4. Source _env.sh (picks up our exports + proxy.env) ──────────────────
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_env.sh"

echo "=== [00a] Setup osediff env on WSL ==="
echo "  🤖 OSEDiff:    $OSEDIFF_DIR"
echo "  🏋️ weights:    $MODEL_DIR"
echo "  💾 output:     $RESULTS_DIR"
echo "  🏋️ train out:  $EXPERIMENTS_DIR"
echo "  🐍 conda env:  $CONDA_ENV  (at $CONDA_PREFIX)"
echo ""

# ── 5. Create osediff env from scratch ───────────────────────────────────
_new_prefix="$(conda info --base 2>/dev/null)/envs/$CONDA_ENV"
if [ -d "$_new_prefix/conda-meta" ] && [ -f "$_new_prefix/conda-meta/history" ]; then
    echo "--- conda env '$CONDA_ENV' already exists at $_new_prefix ---"
else
    echo "📦 creating conda env '$CONDA_ENV' (python=3.10) from scratch..."
    conda create -y -n "$CONDA_ENV" python=3.10 || {
        echo "❌ conda create failed" >&2
        exit 1
    }
    echo "  ✅ created"
fi

# shellcheck disable=SC1091
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"
echo "  🐍 python: $(python --version 2>&1) at $(which python)"

# Verify CPython (not GraalPy — gxx_linux-64 can cause a swap).
_impl="$(python -c "import platform; print(platform.python_implementation())" 2>/dev/null)"
if [ "$_impl" != "CPython" ]; then
    echo "❌ ERROR: python is $_impl, not CPython. Recreate env:" >&2
    echo "       conda env remove -n $CONDA_ENV && bash $0" >&2
    exit 1
fi

# ── 6. Install PyTorch (pip, cu118 — matches requirements.txt torch==2.0.1) ─
# RTX 3090 (sm_86) supports cu118. download.pytorch.org reachable from home.
TORCH_INDEX_URL="${TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu118}"
if ! python -c "import torch; assert torch.cuda.is_available()" 2>/dev/null; then
    echo "📦 installing PyTorch (torch==2.0.1, cu118)..."
    pip install --index-url "$TORCH_INDEX_URL" torch==2.0.1 torchvision==0.15.2 || {
        echo "❌ torch install failed" >&2
        echo "  Try cu117: TORCH_INDEX_URL=https://download.pytorch.org/whl/cu117 bash $0" >&2
        echo "  Or PyPI default: pip install torch==2.0.1" >&2
        exit 1
    }
fi
python -c "import torch; print(f'  ✅ torch {torch.__version__}  cuda={torch.version.cuda}  available={torch.cuda.is_available()}')"

# ── 7. Install xformers (prebuilt wheel for torch 2.0.1) ──────────────────
# requirements.txt pins xformers==0.0.20; a prebuilt wheel exists for torch2.0.1.
# If the wheel is missing, fallback to conda nvcc + source build (slow).
if ! python -c "import xformers; import xformers.ops" 2>/dev/null; then
    echo "📦 installing xformers==0.0.20 (prebuilt wheel)..."
    if ! pip install xformers==0.0.20 2>&1; then
        echo "  ⚠️ prebuilt wheel unavailable; installing nvcc + building from source..."
        # CUDA toolkit via conda (no sudo). cuda-nvcc ~50MB, not the full ~2GB.
        CUDA_TOOLKIT_LABEL="${CUDA_TOOLKIT_LABEL:-nvidia/label/cuda-12.1.1}"
        conda install -y -c "$CUDA_TOOLKIT_LABEL" cuda-nvcc cuda-cudart-dev cuda-cccl || \
            echo "  ⚠️ cuda-nvcc install failed" >&2
        conda install -y -c conda-forge gxx_linux-64=12 python=3.10 || \
            echo "  ⚠️ gxx install failed" >&2
        export CUDA_HOME="${CUDA_HOME:-$CONDA_PREFIX}"
        export PATH="$CUDA_HOME/bin:$PATH"
        _gcc="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc"
        _gpp="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++"
        [ -x "$_gcc" ] && export CC="$_gcc"
        [ -x "$_gpp" ] && export CXX="$_gpp"
        pip install --no-build-isolation xformers==0.0.20 || \
            echo "  ❌ xformers source build failed — inference will fall back to vanilla attn" >&2
    fi
fi
python -c "import xformers.ops; print('  ✅ xformers ops available')" 2>/dev/null || \
    echo "  [---] xformers not importable (training -O2 will need it; inference can run without)"

# ── 8. Install the rest of OSEDiff requirements ──────────────────────────
PIP_FLAGS=(--timeout 600 --retries 10)
# Tsinghua mirror (faster in CN); harmless elsewhere if proxy.env unset it.
[ -n "${PIP_INDEX_URL:-}" ] && PIP_FLAGS+=(--index-url "$PIP_INDEX_URL")
[ -n "${PIP_TRUSTED_HOST:-}" ] && PIP_FLAGS+=(--trusted-host "$PIP_TRUSTED_HOST")

if [ "${INSTALL_DEPS:-1}" = "1" ]; then
    # Clone first so requirements.txt is available (step 9 also clones; idempotent).
    mkdir -p "$(dirname "$OSEDIFF_DIR")"
    if [ ! -d "$OSEDIFF_DIR/.git" ]; then
        echo "📦 cloning OSEDiff -> $OSEDIFF_DIR"
        git clone "$OSEDIFF_REPO" "$OSEDIFF_DIR" || \
            git -c http.sslVerify=false clone "$OSEDIFF_REPO" "$OSEDIFF_DIR"
    fi
    REQ="$OSEDIFF_DIR/requirements.txt"
    if [ -f "$REQ" ]; then
        echo "📦 installing OSEDiff requirements (skipping torch/xformers already pinned)..."
        # Skip torch/torchvision/xformers lines — installed above with the right CUDA build.
        TMP_REQ="$(mktemp).txt"
        grep -v -iE '^[[:space:]]*(torch|torchvision|xformers)([=<>!~]|$|[[:space:]])' "$REQ" > "$TMP_REQ"
        pip install "${PIP_FLAGS[@]}" -r "$TMP_REQ" || echo "  ⚠️ some requirements failed" >&2
        rm -f "$TMP_REQ"
    else
        echo "  ⚠️ $REQ not found (repo not cloned yet?)" >&2
    fi
else
    echo "⏭️  INSTALL_DEPS!=1 — skipping requirements install"
fi

# ── 9. Clone OSEDiff official repo ────────────────────────────────────────
mkdir -p "$(dirname "$OSEDIFF_DIR")"
if [ ! -d "$OSEDIFF_DIR/.git" ]; then
    echo "📦 cloning OSEDiff -> $OSEDIFF_DIR"
    git clone "$OSEDIFF_REPO" "$OSEDIFF_DIR" || \
        git -c http.sslVerify=false clone "$OSEDIFF_REPO" "$OSEDIFF_DIR"
else
    echo "⏭️  OSEDiff already present: $OSEDIFF_DIR"
fi

# ── 10. conda init bash (so interactive shells have conda on PATH) ────────
if ! grep -q "miniconda3" "$HOME/.bashrc" 2>/dev/null; then
    echo "📦 running 'conda init bash'..."
    conda init bash
    echo "  ✅ conda initialized in ~/.bashrc"
    echo "  ⚠️ Run 'source ~/.bashrc' or restart your shell before running scripts 01-08"
else
    echo "⏭️  conda already initialized in ~/.bashrc"
fi

# ── 11. Verify ────────────────────────────────────────────────────────────
echo ""
echo "--- verification ---"
[ -d "$OSEDIFF_DIR/.git" ] && echo "  ✅ OSEDiff code: $OSEDIFF_DIR" || echo "  [MISS] OSEDiff code"
[ -f "$OSEDIFF_PKL" ] && echo "  ✅ osediff.pkl (repo-shipped): $(du -h "$OSEDIFF_PKL" | cut -f1)" || \
    echo "  [MISS] osediff.pkl (should be in preset/models/ after clone)"
python -c "import torch; print(f'  ✅ torch {torch.__version__} cuda={torch.cuda.is_available()}')" 2>/dev/null || echo "  [MISS] torch"
python -c "import diffusers, transformers, peft; print('  ✅ diffusers/transformers/peft')" 2>/dev/null || \
    echo "  [MISS] diffusers/transformers/peft (run INSTALL_DEPS=1 bash $0)"
python -c "import xformers.ops; print('  ✅ xformers')" 2>/dev/null || echo "  [---] xformers (optional; training needs it)"

echo ""
echo "🎉 [00a] Done. Next:"
echo "  1. source ~/.bashrc  (activate conda for your shell)"
echo "  2. GPU=0 bash osediff/01_download_models.sh   # SD2.1-base + RAM (~7GB)"
echo "  3. GPU=0 bash osediff/02_run_inference.sh      # super-resolve preset test images"
