#!/usr/bin/env bash
# 00a_setup_env.sh — WSL Ubuntu 24.04 variant of 00_setup_env.sh.
#
# Differences from 00_setup_env.sh (server):
# - Creates vggt_human env from scratch (python=3.10 + pip torch cu121),
#   NOT a cp -a clone of the server's `doll` env (which doesn't exist on WSL).
# - Installs CUDA toolkit (nvcc) + gcc via conda — no sudo / apt needed.
# - Clones repos to ~/repos/ and weights to ~/model/ (Linux filesystem,
#   fast I/O — compiling CUDA exts on /mnt/c is slow and error-prone).
# - Writes WSL path overrides to proxy.env so scripts 01-07 pick them up
#   automatically (no need to set env vars every time).
# - Runs `conda init bash` so interactive shells have conda on PATH.
# - No corporate proxy / CA bundle workarounds (direct internet at home).
#
# Usage:
#   bash vggt_human/00a_setup_env.sh              # full setup
#   INSTALL_DENOISER=1 bash vggt_human/00a_setup_env.sh  # + DiffBIR/SwinIR
#
# Override CUDA version (default 12.1):
#   CUDA_TOOLKIT_LABEL=nvidia/label/cuda-12.4.0 \
#   TORCH_INDEX_URL=https://download.pytorch.org/whl/cu124 \
#   bash vggt_human/00a_setup_env.sh
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"

# ── 1. Source conda (must exist; miniconda3 at ~/miniconda3) ──────────────
CONDA_BASE="$HOME/miniconda3"
if [ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]; then
    echo "❌ ERROR: miniconda3 not found at $CONDA_BASE" >&2
    echo "       Install first:" >&2
    echo "         curl -fsSL https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh" >&2
    echo "         bash /tmp/miniconda.sh -b -p $CONDA_BASE" >&2
    exit 1
fi
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# Accept ToS for default channels (conda 26.x requires it; older versions ignore).
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main 2>/dev/null || true
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r 2>/dev/null || true

# ── 2. WSL path defaults (Linux fs: repos ~/repos, weights ~/model) ───────
# Exported BEFORE sourcing _env.sh so its ${VAR:-default} picks these up.
# Also written to proxy.env (step 3) so scripts 01-07 inherit them.
# Repos + weights on Linux filesystem (fast I/O for compilation + training).
export VGGT_DIR="${VGGT_DIR:-$HOME/repos/vggt-omega}"
export GS_DIR="${GS_DIR:-$HOME/repos/gaussian-splatting}"
export MODEL_DIR="${MODEL_DIR:-/mnt/d/wheel/vggt_human_ms/VGGT-Omega}"
export RESULTS_DIR="${RESULTS_DIR:-$HOME/output/vggt_human_results}"
export HYPIR_DIR="${HYPIR_DIR:-$HOME/repos/HYPIR}"
export WEIGHTS_ROOT="${WEIGHTS_ROOT:-/mnt/d/wheel/vggt_human_ms}"
export DIFFBIR_DIR="${DIFFBIR_DIR:-$HOME/repos/DiffBIR}"
export SWINIR_DIR="${SWINIR_DIR:-$HOME/repos/SwinIR}"

# ── 3. Write proxy.env with WSL path overrides (if not exists) ────────────
# proxy.env is at repo root ($REPO_DIR/proxy.env), gitignored.
# _env.sh sources it before setting ${VAR:-default} defaults, so all scripts
# 01-07 will automatically use the WSL Linux-filesystem paths.
PROXY_ENV="$REPO_DIR/proxy.env"
if [ ! -f "$PROXY_ENV" ]; then
    echo "📦 writing WSL path overrides -> $PROXY_ENV"
    cat > "$PROXY_ENV" <<'ENVEOF'
# proxy.env — WSL Ubuntu 24.04 path overrides (auto-generated by 00a_setup_env.sh).
# No corporate proxy needed (direct internet). Just path overrides + HF_TOKEN.
#
# ⚠️ Fill HF_TOKEN before running step 02 (VGGT-Omega weights are gated):
#    1. Request access: https://huggingface.co/facebook/VGGT-Omega
#    2. Create token:  https://huggingface.co/settings/tokens
#    3. Uncomment + fill below:
# export HF_TOKEN="hf_xxx"

# HF mirror (huggingface.co 直连超时; 用 hf-mirror.com 镜像)
export HF_ENDPOINT="https://hf-mirror.com"

# Repos on Linux fs (compilation); Models on D:\wheel (read once, no copy needed).
export VGGT_DIR="$HOME/repos/vggt-omega"
export GS_DIR="$HOME/repos/gaussian-splatting"
export HYPIR_DIR="$HOME/repos/HYPIR"
export MODEL_DIR="/mnt/d/wheel/vggt_human_ms/VGGT-Omega"
export WEIGHTS_ROOT="/mnt/d/wheel/vggt_human_ms"
export RESULTS_DIR="${RESULTS_DIR:-$HOME/output/vggt_human_results}"
export DIFFBIR_DIR="$HOME/repos/DiffBIR"
export SWINIR_DIR="$HOME/repos/SwinIR"
# 动态掩码模型（D 盘直接读）
export SAM2_MODEL_PATH="/mnt/d/wheel/vggt_human_ms/sam2"
export SAM2_DIR="$HOME/repos/segment-anything-2"
export SAM2_CONFIG="configs/sam2.1/sam2.1_hiera_l.yaml"
export GROUNDING_DINO_ID="/mnt/d/wheel/vggt_human_ms/grounding-dino-tiny"
export DINO_MODEL_PATH="/mnt/d/wheel/vggt_human_ms/dinov2/dinov2_vits14_reg4_pretrain.pth"
# sam2 包不 pip install，直接加 PYTHONPATH
export PYTHONPATH="$HOME/repos/segment-anything-2:$PYTHONPATH"
ENVEOF
    echo "  ✅ written (edit to add HF_TOKEN before step 02)"
else
    echo "⏭️  proxy.env already exists: $PROXY_ENV (not overwriting)"
fi

# ── 4. Source _env.sh (picks up our exports + proxy.env) ──────────────────
# _env.sh: proxy.env sourcing, conda activate, GPU, paths, all the exports.
# shellcheck disable=SC1091
source "$SCRIPT_DIR/_env.sh"

echo "=== [00a] Setup vggt_human env on WSL ==="
echo "  🤖 VGGT-Omega:  $VGGT_DIR"
echo "  🎮 3DGS:        $GS_DIR"
echo "  🏋️ weights:     $MODEL_DIR"
echo "  💾 output:      $RESULTS_DIR"
echo "  🏠 conda env:   $CONDA_ENV  (at $CONDA_PREFIX)"
echo ""

# ── 5. Create vggt_human env from scratch (no doll clone) ─────────────────
_new_prefix="$(conda info --base 2>/dev/null)/envs/$CONDA_ENV"
if [ -d "$_new_prefix/conda-meta" ] && [ -f "$_new_prefix/conda-meta/history" ]; then
    echo "--- conda env '$CONDA_ENV' already exists at $_new_prefix ---"
else
    echo "📦 creating conda env '$CONDA_ENV' (python=3.10) from scratch..."
    conda create -y -n "$CONDA_ENV" python=3.10 || {
        echo "❌ conda create failed" >&2
        exit 1
    }
    echo "  ✅ created"
fi

# Activate
# shellcheck disable=SC1091
source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "$CONDA_ENV"
echo "  🐍 python: $(python --version 2>&1) at $(which python)"

# Verify CPython (not GraalPy — gxx_linux-64 can cause a swap).
_impl="$(python -c "import platform; print(platform.python_implementation())" 2>/dev/null)"
if [ "$_impl" != "CPython" ]; then
    echo "❌ ERROR: python is $_impl, not CPython. Recreate env:" >&2
    echo "       conda env remove -n $CONDA_ENV && bash $0" >&2
    exit 1
fi

# ── 6. Install PyTorch (pip, cu121) ───────────────────────────────────────
# Local wheels in /mnt/d/wheel take priority; missing ones from download.pytorch.org.
TORCH_INDEX_URL="${TORCH_INDEX_URL:-https://download.pytorch.org/whl/cu121}"
WHEELS_DIR="${WHEELS_DIR:-/mnt/d/wheel}"
if ! python -c "import torch; assert torch.cuda.is_available()" 2>/dev/null; then
    echo "📦 installing PyTorch (cu121)..."
    mkdir -p "$WHEELS_DIR"
    pip install --index-url "$TORCH_INDEX_URL" --find-links "$WHEELS_DIR" \
        --timeout 600 --retries 5 torch torchvision || {
        echo "❌ torch install failed" >&2
        echo "  Try cu124: TORCH_INDEX_URL=https://download.pytorch.org/whl/cu124 bash $0" >&2
        exit 1
    }
fi
python -c "import torch; print(f'  ✅ torch {torch.__version__}  cuda={torch.version.cuda}  available={torch.cuda.is_available()}')"

# ── 7. Install CUDA toolkit (nvcc) + gcc via conda ────────────────────────
# No sudo needed — everything goes into the conda env prefix.
# nvcc is required to compile diff-gaussian-rasterization + simple-knn.
# gcc 12 matches CUDA 12.x; python=3.10 pinned to prevent GraalPy swap.
CUDA_TOOLKIT_LABEL="${CUDA_TOOLKIT_LABEL:-nvidia/label/cuda-12.1.1}"

if ! command -v nvcc >/dev/null 2>&1; then
    echo "📦 installing CUDA toolkit ($CUDA_TOOLKIT_LABEL)..."
    conda install -y -c "$CUDA_TOOLKIT_LABEL" cuda-toolkit || {
        echo "❌ cuda-toolkit install failed" >&2
        echo "  Try: CUDA_TOOLKIT_LABEL=nvidia/label/cuda-12.4.0 bash $0" >&2
        exit 1
    }
fi
echo "  ✅ nvcc: $(nvcc --version 2>/dev/null | tail -1 | xargs)"

if ! command -v x86_64-conda-linux-gnu-gcc >/dev/null 2>&1; then
    echo "📦 installing gcc 12 (gxx_linux-64, python=3.10 pinned)..."
    conda install -y -c conda-forge gxx_linux-64=12 python=3.10 || {
        echo "  ⚠️ gxx install failed; trying system gcc" >&2
    }
fi
_gcc="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-gcc"
_gpp="$CONDA_PREFIX/bin/x86_64-conda-linux-gnu-g++"
if [ -x "$_gcc" ] && [ -x "$_gpp" ]; then
    echo "  ✅ gcc: $($_gcc --version | head -1)"
else
    echo "  ⚠️ conda gcc not found; trying system gcc/g++" >&2
    command -v gcc >/dev/null 2>&1 && echo "  gcc: $(gcc --version | head -1)" || echo "  ❌ no gcc" >&2
fi

# ── 8. Install pip deps ───────────────────────────────────────────────────
# pip: 先查本地 wheel (/mnt/d/wheel)，缺的从清华镜像补。
WHEELS_DIR="${WHEELS_DIR:-/mnt/d/wheel}"
mkdir -p "$WHEELS_DIR"
PIP_FLAGS=(-i https://pypi.tuna.tsinghua.edu.cn/simple --find-links "$WHEELS_DIR" \
    --timeout 600 --retries 5)

echo "📦 installing VGGT-Omega runtime deps..."
pip install "${PIP_FLAGS[@]}" "numpy<2" Pillow einops safetensors opencv-python \
    huggingface_hub || echo "  ⚠️ some VGGT-Omega deps failed" >&2

echo "📦 installing 3DGS + mediapipe runtime deps..."
pip install "${PIP_FLAGS[@]}" plyfile tqdm torchmetrics lpips \
    scipy trimesh matplotlib "mediapipe==0.10.14" || echo "  ⚠️ some 3DGS deps failed" >&2

echo "📦 installing HYPIR deps (diffusers, transformers, peft)..."
pip install "${PIP_FLAGS[@]}" "diffusers==0.32.2" "transformers==4.49.0" "peft==0.14.0" \
    omegaconf kornia accelerate || echo "  ⚠️ some HYPIR deps failed" >&2

# Pin numpy (conda may have touched it)
pip install "${PIP_FLAGS[@]}" --force-reinstall --no-deps numpy==1.26.4

# ── 9. Clone official repos ────────────────────────────────────────────────
mkdir -p "$(dirname "$VGGT_DIR")" "$(dirname "$GS_DIR")"

# VGGT-Omega (vggt-omega/00 already clones on server; on WSL we clone fresh)
if [ ! -d "$VGGT_DIR/.git" ]; then
    echo "📦 cloning VGGT-Omega -> $VGGT_DIR"
    git clone "$VGGT_REPO" "$VGGT_DIR" || \
        git -c http.sslVerify=false clone "$VGGT_REPO" "$VGGT_DIR"
else
    echo "⏭️  VGGT-Omega already present: $VGGT_DIR"
fi

# gaussian-splatting (original 3DGS)
if [ ! -d "$GS_DIR/.git" ]; then
    echo "📦 cloning gaussian-splatting -> $GS_DIR"
    git clone "$GS_REPO" "$GS_DIR" || \
        git -c http.sslVerify=false clone "$GS_REPO" "$GS_DIR"
fi

# Ensure submodules (diff-gaussian-rasterization, simple-knn, GLM)
SUBMOD_DIR="$GS_DIR/submodules"
if [ ! -f "$SUBMOD_DIR/diff-gaussian-rasterization/setup.py" ] || \
   [ ! -f "$SUBMOD_DIR/simple-knn/setup.py" ]; then
    echo "📦 ensuring gaussian-splatting submodules"
    # Replace gitlab.inria.fr submodule URLs with GitHub mirrors
    if [ -f "$GS_DIR/.gitmodules" ]; then
        git -C "$GS_DIR" config -f .gitmodules submodule.submodules/simple-knn.url https://github.com/yindaheng98/simple-knn.git
        git -C "$GS_DIR" config -f .gitmodules submodule.third_party/glm.url https://github.com/g-truc/glm.git || true
        git -C "$GS_DIR" config -f .gitmodules submodule.submodules/SIBR_viewers.url https://github.com/graphdeco-inria/SIBR_viewers.git 2>/dev/null || true
        git -C "$GS_DIR" submodule sync
    fi
    ( cd "$GS_DIR" && git submodule update --init --recursive ) || \
        ( cd "$GS_DIR" && git -c http.sslVerify=false submodule update --init --recursive ) || true

    # diff-gaussian-rasterization
    if [ ! -f "$SUBMOD_DIR/diff-gaussian-rasterization/setup.py" ]; then
        echo "  📦 cloning diff-gaussian-rasterization"
        rm -rf "$SUBMOD_DIR/diff-gaussian-rasterization"
        git clone https://github.com/graphdeco-inria/diff-gaussian-rasterization.git \
            "$SUBMOD_DIR/diff-gaussian-rasterization" || \
            git -c http.sslVerify=false clone \
                https://github.com/graphdeco-inria/diff-gaussian-rasterization.git \
                "$SUBMOD_DIR/diff-gaussian-rasterization"
    fi

    # simple-knn (try multiple mirrors)
    if [ ! -f "$SUBMOD_DIR/simple-knn/setup.py" ]; then
        echo "  📦 cloning simple-knn"
        rm -rf "$SUBMOD_DIR/simple-knn"
        _sk_done=false
        for _sk_url in \
            "https://gitlab.inria.fr/bkerbl/simple-knn.git" \
            "https://github.com/yindaheng98/simple-knn.git" \
            "https://github.com/jteng2127/simple-knn.git"; do
            if git clone "$_sk_url" "$SUBMOD_DIR/simple-knn" 2>/dev/null || \
               git -c http.sslVerify=false clone "$_sk_url" "$SUBMOD_DIR/simple-knn" 2>/dev/null; then
                _sk_done=true
                echo "    ✅ cloned from $_sk_url"
                break
            fi
            rm -rf "$SUBMOD_DIR/simple-knn"
        done
        [ "$_sk_done" = "true" ] || echo "  ❌ simple-knn clone failed (all mirrors)" >&2
    fi

    # GLM (header-only math lib, diff-gaussian-rasterization needs it)
    GLM_DIR="$GS_DIR/third_party/glm"
    if [ ! -f "$GLM_DIR/glm/glm.hpp" ]; then
        echo "  📦 cloning GLM"
        rm -rf "$GLM_DIR"
        git clone https://github.com/g-truc/glm.git "$GLM_DIR" || \
            git -c http.sslVerify=false clone https://github.com/g-truc/glm.git "$GLM_DIR"
    fi
fi

# ── 10. Compile CUDA extensions ────────────────────────────────────────────
export CUDA_HOME="${CUDA_HOME:-$CONDA_PREFIX}"
export PATH="$CUDA_HOME/bin:$PATH"

# Resolve CC/CXX to conda gcc12 (matches CUDA 12.x)
if [ -x "$_gcc" ] && [ -x "$_gpp" ]; then
    export CC="$_gcc"; export CXX="$_gpp"
fi

_DGR="$SUBMOD_DIR/diff-gaussian-rasterization"
if [ -f "$_DGR/setup.py" ] || [ -f "$_DGR/pyproject.toml" ]; then
    # Switch to dr_aa branch (antialiasing; gaussian_renderer uses antialiasing=pipe.antialiasing)
    _cur_branch="$(cd "$_DGR" && git branch --show-current 2>/dev/null || echo '')"
    if [ "$_cur_branch" != "dr_aa" ]; then
        echo "  📦 switching diff-gaussian-rasterization: '$_cur_branch' -> 'dr_aa'"
        ( cd "$_DGR" && git checkout dr_aa ) || echo "  ⚠️ checkout dr_aa failed" >&2
    fi
    echo "🔨 building CUDA ext: diff-gaussian-rasterization (dr_aa, antialiasing)"
    rm -rf "$_DGR/build" "$_DGR/dist" "$_DGR"/*.egg-info
    # GLM symlink: diff-gaussian-rasterization's third_party/glm may be empty
    if [ ! -f "$_DGR/third_party/glm/glm/glm.hpp" ] && [ -f "$GS_DIR/third_party/glm/glm/glm.hpp" ]; then
        rm -rf "$_DGR/third_party/glm"
        ln -sf "$GS_DIR/third_party/glm" "$_DGR/third_party/glm"
    fi
    pip install --no-build-isolation --no-deps "$_DGR" || \
        echo "  ❌ diff-gaussian-rasterization build failed" >&2
else
    echo "  ⚠️ skip diff-gaussian-rasterization: setup.py not found" >&2
fi

_SK="$SUBMOD_DIR/simple-knn"
if [ -f "$_SK/setup.py" ]; then
    echo "🔨 building CUDA ext: simple-knn"
    pip install --no-build-isolation --no-deps "$_SK" || \
        echo "  ❌ simple-knn build failed" >&2
fi

python -c "import diff_gaussian_rasterization, simple_knn; print('  ✅ CUDA exts importable')" 2>/dev/null || \
    echo "  ⚠️ CUDA exts not importable yet" >&2

# ── 11. Clone HYPIR + download SD2 base model (optional) ─────────────────
# Set SKIP_HYPIR=1 to skip (step 01/06 face enhancement disabled until ready).
if [ "${SKIP_HYPIR:-0}" != "1" ]; then
    mkdir -p "$(dirname "$HYPIR_DIR")" "$HYPIR_MODEL_DIR"
    if [ ! -d "$HYPIR_DIR/.git" ]; then
        echo "📦 cloning HYPIR -> $HYPIR_DIR"
        git clone https://github.com/XPixelGroup/HYPIR.git "$HYPIR_DIR" || \
            git -c http.sslVerify=false clone https://github.com/XPixelGroup/HYPIR.git "$HYPIR_DIR"
    fi
    if [ ! -d "$HYPIR_BASE_MODEL" ]; then
        echo "📦 downloading SD2 base model -> $HYPIR_BASE_MODEL (large, ~5GB)..."
        git clone https://huggingface.co/stabilityai/stable-diffusion-2-base "$HYPIR_BASE_MODEL" || \
            git -c http.sslVerify=false clone https://huggingface.co/stabilityai/stable-diffusion-2-base "$HYPIR_BASE_MODEL" || \
            echo "  ⚠️ SD2 base model download failed. Manual:" >&2
        echo "    git clone https://huggingface.co/stabilityai/stable-diffusion-2-base $HYPIR_BASE_MODEL" >&2
    fi
else
    echo "⏭️  SKIP_HYPIR=1 — skipping HYPIR + SD2 base (step 01/06 disabled)"
fi

# ── 12. Optional: denoiser models (DiffBIR / SwinIR) ──────────────────────
if [ "${INSTALL_DENOISER:-0}" = "1" ]; then
    echo "📦 installing denoiser models (INSTALL_DENOISER=1)..."
    # DiffBIR
    if [ ! -d "$DIFFBIR_DIR/.git" ]; then
        echo "  📦 cloning DiffBIR -> $DIFFBIR_DIR"
        mkdir -p "$(dirname "$DIFFBIR_DIR")"
        git clone "$DIFFBIR_REPO" "$DIFFBIR_DIR" || \
            git -c http.sslVerify=false clone "$DIFFBIR_REPO" "$DIFFBIR_DIR"
    fi
    mkdir -p "$(dirname "$DIFFBIR_CKPT")"
    if [ ! -s "$DIFFBIR_CKPT" ]; then
        echo "  📦 downloading DiffBIR checkpoint..."
        wget --no-check-certificate -q -O "$DIFFBIR_CKPT" \
            "https://huggingface.co/zhonghuiyi/ckpt/resolve/main/cldm.pth" || true
        [ -s "$DIFFBIR_CKPT" ] || echo "  ⚠️ DiffBIR ckpt download failed" >&2
    fi
    pip install "${PIP_FLAGS[@]}" diffusers omegaconf einops kornia || true

    # SwinIR
    if [ ! -d "$SWINIR_DIR/.git" ]; then
        echo "  📦 cloning SwinIR -> $SWINIR_DIR"
        mkdir -p "$(dirname "$SWINIR_DIR")"
        git clone "$SWINIR_REPO" "$SWINIR_DIR" || \
            git -c http.sslVerify=false clone "$SWINIR_REPO" "$SWINIR_DIR"
    fi
    mkdir -p "$(dirname "$SWINIR_CKPT")"
    if [ ! -s "$SWINIR_CKPT" ]; then
        echo "  📦 downloading SwinIR checkpoint..."
        wget --no-check-certificate -q -O "$SWINIR_CKPT" \
            "https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/001_classicalSR_DIV2K_s128w8_SwinIR-M_x4.pth" || true
        [ -s "$SWINIR_CKPT" ] || echo "  ⚠️ SwinIR ckpt download failed" >&2
    fi
fi

# ── 13. conda init bash (so interactive shells have conda on PATH) ─────────
if ! grep -q "miniconda3" "$HOME/.bashrc" 2>/dev/null; then
    echo "📦 running 'conda init bash'..."
    conda init bash
    echo "  ✅ conda initialized in ~/.bashrc"
    echo "  ⚠️ Run 'source ~/.bashrc' or restart your shell before running scripts 01-07"
else
    echo "⏭️  conda already initialized in ~/.bashrc"
fi

# ── 14. Verify ─────────────────────────────────────────────────────────────
echo ""
echo "--- verification ---"
[ -d "$VGGT_DIR/vggt_omega" ] && echo "  ✅ VGGT-Omega code" || echo "  [MISS] VGGT-Omega code: $VGGT_DIR"
[ -f "$GS_DIR/train.py" ] && echo "  ✅ 3DGS train.py" || echo "  [MISS] 3DGS: $GS_DIR"
python -c "import torch; print(f'  ✅ torch {torch.__version__} cuda={torch.cuda.is_available()}')" 2>/dev/null || echo "  [MISS] torch"
python -c "import diff_gaussian_rasterization, simple_knn; print('  ✅ CUDA exts')" 2>/dev/null || \
    echo "  [MISS] CUDA exts (build may have failed — check errors above)"
python -c "import mediapipe; print('  ✅ mediapipe')" 2>/dev/null || echo "  [MISS] mediapipe"
[ -d "$HYPIR_DIR/.git" ] && echo "  ✅ HYPIR code" || echo "  [---] HYPIR code (SKIP_HYPIR=1; step 01/06 disabled)"
[ -d "$HYPIR_BASE_MODEL" ] && echo "  ✅ SD2 base model" || echo "  [---] SD2 base model (huggingface.co unreachable; needed for step 01/06)"

# VGGT-Omega weights (gated — user must download separately)
if [ -f "$MODEL_DIR/vggt_omega_1b_512.pt" ]; then
    echo "  ✅ VGGT-Omega weights (1b_512)"
else
    echo "  [---] VGGT-Omega weights (gated — run vggt-omega/01_download_models.sh with HF_TOKEN)"
fi

echo ""
echo "🎉 [00a] Done. Next:"
echo "  1. Fill HF_TOKEN in $PROXY_ENV (for step 02 VGGT-Omega weights)"
echo "  2. source ~/.bashrc  (activate conda for your shell)"
echo "  3. GPU=0 INPUT_DIR=~/my_images RESULTS_DIR=~/output/vggt_human_results \\"
echo "         bash vggt_human/01_face_enhance.sh"
